### PR TITLE
crd validation

### PR DESCRIPTION
**Pull request by tchughesiv**
resolves https://github.com/font/gatekeeper-operator/issues/6

Signed-off-by: tchughesiv <tchughesiv@gmail.com>

### CODE REVIEW

**Comment by tchughesiv** [comment]
@font am i on the right track here? anything else you'd like to see?

**Comment by font** [comment]
Thanks @tchughesiv, this is a great start! It's definitely on the right track. I think we could try to add validation markers for all the fields of the API wherever possible e.g. replicas, any image config fields possible, etc.

**Comment by tchughesiv** [comment]
@font I've added additional validation and a manifest check to our CI. Let me know if there's anything else you'd like to see in this PR.

**Review by font — APPROVED** [review]
Thanks @tchughesiv !

**Pull request merged**
